# Generated by Django 5.1.4 on 2025-08-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0003_student_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
